GENERIC_DESKTOP={
  'Pointer': 0x1,
  'Mouse': 0x2,
  'Joystick': 0x4,
  'Gamepad': 0x5,
  'Keyboard': 0x6,
  'Keypad': 0x7,
  'Multi-axis Controller': 0x8,
  'Tablet PC System Controls': 0x9,
  'Water Cooling Device': 0x0A,
  'Computer Chassis Device': 0x0B,
  'Wireless Radio Controls': 0x0C,
  'Portable Device Control': 0x0D,
  'System Multi-Axis Controller': 0x0E,
  'Spatial Controller': 0x0F,
  'Assistive Control': 0x10,
  'Device Dock': 0x11,
  'Dockable Device': 0x12,
  'X': 0x30,
  'Y': 0x31,
  'Z': 0x32,
  'Rx': 0x33,
  'Ry': 0x34,
  'Rz': 0x35,
  'Slider': 0x36,
  'Dial': 0x37,
  'Wheel': 0x38,
  'Hat Switch': 0x39,
  'Counted Buffer': 0x3A,
  'Byte Count': 0x3B,
  'Motion Wakeup': 0x3C,
  'Start': 0x3D,
  'Select': 0x3E,
  'Vx': 0x40,
  'Vy': 0x41,
  'Vz': 0x42,
  'Vbrx': 0x43,
  'Vbry' : 0x44,
  'Vbrz' : 0x45,
  'Vno' : 0x46,
  'Feature Notification' : 0x47,
  'Resolution Multiplier' : 0x48,
  'Qx' : 0x49,
  'Qy' : 0x4A,
  'Qz' : 0x4B,
  'Qw' : 0x4C,
  'System Control' : 0x80,
  'System Power Down' : 0x81,
  'System Sleep' : 0x82,
  'System Wake Up' : 0x83,
  'System Context Menu' : 0x84,
  'System Main Menu' : 0x85,
  'System App Menu' : 0x86,
  'System Menu Help' : 0x87,
  'System Menu Exit' : 0x88,
  'System Menu Select' : 0x89,
  'System Menu Right' : 0x8A,
  'System Menu Left' : 0x8B,
  'System Menu Up' : 0x8C,
  'System Menu Down' : 0x8D,
  'System Cold Restart' : 0x8E,
  'System Warm Restart' : 0x8F,
  'D-pad Up' : 0x90,
  'D-pad Down' : 0x91,
  'D-pad Right' : 0x92,
  'D-pad Left' : 0x93,
  'Index Trigger' : 0x94,
  'Palm Trigger' : 0x95,
  'Thumbstick' : 0x96,
  'System Function Shift' : 0x97,
  'System Function Shift Lock' : 0x98,
  'System Function Shift Lock Indicator' : 0x99,
  'System Dismiss Notification' : 0x9A,
  'System Do Not Disturb' : 0x9B,
  'System Dock' : 0xA0,
  'System Undock' : 0xA1,
  'System Setup' : 0xA2,
  'System Break' : 0xA3,
  'System Debugger Break' : 0xA4,
  'Application Break' : 0xA5,
  'Application Debugger Break' : 0xA6,
  'System Speaker Mute' : 0xA7,
  'System Hibernate' : 0xA8,
  'System Display Invert' : 0xB0,
  'System Display Internal' : 0xB1,
  'System Display External' : 0xB2,
  'System Display Both' : 0xB3,
  'System Display Dual' : 0xB4,
  'System Display Toggle Int/Ext Mode' : 0xB5,
  'System Display Swap Primary/Secondary' : 0xB6,
  'System Display Toggle LCD Autoscale' : 0xB7,
  'Sensor Zone' : 0xC0,
  'RPM' : 0xC1,
  'Coolant Level' : 0xC2,
  'Coolant Critical Level' : 0xC3,
  'Coolant Pump' : 0xC4,
  'Chassis Enclosure' : 0xC5,
  'Wireless Radio Button' : 0xC6,
  'Wireless Radio LED' : 0xC7,
  'Wireless Radio Slider Switch' : 0xC8,
  'System Display Rotation Lock Button' : 0xC9,
  'System Display Rotation Lock Slider Switch' : 0xCA,
  'Control Enable' : 0xCB,
  'Dockable Device Unique ID' : 0xD0,
  'Dockable Device Vendor ID' : 0xD1,
  'Dockable Device Primary Usage Page' : 0xD2,
  'Dockable Device Primary Usage ID' : 0xD3,
  'Dockable Device Docking State' : 0xD4,
  'Dockable Device Display Occlusion' : 0xD5,
  'Dockable Device Object Type' : 0xD6,
}
